square/rails-auth

- README.md
- lib/rails/auth/error_page/middleware.rb
- lib/rails/auth/rack.rb
- spec/rails/auth/error_page/middleware_spec.rb
This is a middleware that can be used to render a static error page when `Rails::Auth::NotAuthorizedError` is raised by a middleware higher in the chain.
> Add Rails::Auth::ErrorPage::Middleware

- README.md
- lib/rails/auth.rb
- lib/rails/auth/controller_methods.rb
- lib/rails/auth/credentials.rb
- spec/rails/auth/controller_methods_spec.rb
This defines a single method `#credentials` which provides a useful shorthand for accessing `rails-auth.credentials` from the Rack environment. It wraps it in a HashWithIndifferentAccess for easy
access.
> Add Rails::Auth::ControllerMethods

- lib/rails/auth/acl/matchers/allow_all.rb
- lib/rails/auth/x509/certificate.rb
- lib/rails/auth/x509/matcher.rb
- spec/rails/auth/acl/matchers/allow_all_spec.rb
- spec/rails/auth/x509/certificate_spec.rb
- spec/rails/auth/x509/matcher_spec.rb
These are useful with Rails::Auth::ErrorPage::DebugMiddleware
> Add #attributes method to matchers and X.509 certs

- .rubocop.yml
- README.md
- lib/rails/auth/acl.rb
- lib/rails/auth/acl/resource.rb
- spec/rails/auth/acl/resource_spec.rb
For apps that service more than one hostname, it's useful to restrict ACLs by the hostname.
> Support for optionally matching hostnames in ACL resources

- lib/rails/auth/acl/resource.rb
- lib/rails/auth/error_page/debug_page.html.erb
- lib/rails/auth/rspec/helper_methods.rb
- spec/spec_helper.rb
The `PATH_INFO` Rack environment value seems to be present in all Rack contexts, whereas `REQUEST_PATH` is sometimes missing.
> Use PATH_INFO instead of REQUEST_PATH

- README.md
- lib/rails/auth/credentials/injector_middleware.rb
- lib/rails/auth/rack.rb
- spec/rails/auth/credentials/injector_middleware_spec.rb
This middleware supports injecting arbitrary credentials into the Rack environment.
It's useful for development and testing purposes, simulating credentials for a request without actually using other credential middlewares. This lets you simulate being logged in during development, or which credentials clients have in tests.
> Rails::Auth::Credentials::InjectorMiddleware

- lib/rails/auth/acl/resource.rb
- spec/rails/auth/acl/resource_spec.rb
Before ALL functioned as a blanket method whitelist.
This constrains which methods are allowed to the ones in Rails::Auth::ACL::Resource::HTTP_METHODS
> Use explicit HTTP_METHODS whitelist when 'ALL' method is used

- lib/rails/auth/acl/middleware.rb
- lib/rails/auth/override.rb
- lib/rails/auth/rack.rb
- spec/rails/auth/acl/middleware_spec.rb
Add `authorized!(env)` and `authorized?(env)` to `Rails::Auth`. Outside middleware can use `authorized!` to mark a request as being exempt from the ACL check. Allows other authorization systems to play nicely on a per-request basis (for routes that they will already be authorizing, for instance).
> Allow outside middleware to mark a request as authorized

- lib/rails/auth/credentials.rb
- lib/rails/auth/x509/certificate.rb
- lib/rails/auth/x509/filter/pem.rb
- spec/rails/auth/credentials_spec.rb
- spec/rails/auth/x509/certificate_spec.rb
If called with the same type and credentials that return true for `==`, don't raise an ArgumentError. Instead, return the existing env.
Add an `==` implementation to X509::Certificate, comparing the two objects via `certificate.to_der`.
Remove tabs when loading x509 pems via the pem filter.
Built on #25, so the diff will clean up once that merges.
> Make add_credential idempotent

- Gemfile
This library isn't (necessarily) incompatible with Rails 5, however we test on older Rubies, and it's broken on those.
This appears to be due to a Bundler bug:
https://github.com/bundler/bundler/pull/4650
> Lock to Rack 1.x and ActiveSupport 4.x in tests

- lib/rails/auth/x509/filter/java.rb
- spec/rails/auth/x509/middleware_spec.rb
Apparently these are passed into the Rack environment as an array instead of an individual cert, so extract the first one and attempt to verify it.
> Handle javax.servlet.request.X509Certificate arrays

- lib/rails/auth/acl.rb
It's useful to be able to access these for the purpose of debugging authorization failures.
They're frozen anyway, so this hopefully won't have a negative reliability or security impact.
cc @thirstscolr @ewr @zanker
> Add a attr_reader for Rails::Auth::ACL#resources

- lib/rails/auth/error_page/middleware.rb
- spec/rails/auth/error_page/middleware_spec.rb
This detects if a request is for JSON, and if so, renders a JSON response instead of an HTML one.
> Render JSON error responses from Rails::Auth::ErrorPage

- .rubocop.yml
- lib/rails/auth.rb
- lib/rails/auth/config_builder.rb
- lib/rails/auth/rspec/helper_methods.rb
- spec/rails/auth/rspec/helper_methods_spec.rb
- spec/rails/auth/rspec/matchers/acl_matchers_spec.rb
Helper functions which build middleware chains for different environments.
Provides "convention over configuration" when using Rails::Auth inside a Rails app.
> Rails::Auth::ConfigBuilder

- lib/rails/auth/config_builder.rb
- lib/rails/auth/monitor/middleware.rb
- lib/rails/auth/rack.rb
- spec/rails/auth/monitor/middleware_spec.rb
Adds a middleware which fires a callback for every request which includes the Rack environment and whether or not the request was authorized.
Useful for logging AuthZ status of each request and/or reporting AuthZ failures to e.g. an alerting system.
> Rails::Auth::Monitor::Middleware

- lib/rails/auth/acl.rb
- lib/rails/auth/acl/matchers/allow_all.rb
- lib/rails/auth/acl/middleware.rb
- lib/rails/auth/acl/resource.rb
- lib/rails/auth/error_page/debug_page.html.erb
- lib/rails/auth/override.rb
- lib/rails/auth/rack.rb
- lib/rails/auth/result.rb
- lib/rails/auth/x509/matcher.rb
- spec/rails/auth/acl/resource_spec.rb
- spec/rails/auth/acl_spec.rb
Store what authorized the request in the Rack environment.
This involved making some changes to the way ACL#match works to return the matcher that matched the request instead of just true/false.
> Rails::Auth.allowed_by

- lib/rails/auth/override.rb
- spec/rails/auth/acl/middleware_spec.rb
I released 2.0.0 with this as an optional argument, but I really think
it should be mandatory.
Nobody is using 2.0.0 yet, so for maximum semantic versioning correctness
I could yank it to ensure this backward incompatible change is consistent
for all 2.x releases, or just leave it as is and tell people 2.0.0 is
"broken".
Upon updating the spec, I did discover Rails::Auth.authorized! is calling
Rails::Auth.set_allowed_by incorrectly.
> Make allowed_by a mandatory argument of Rails::Auth.authorized!

- lib/rails/auth/credentials.rb
- spec/rails/auth/credentials_spec.rb
Changes Rails::Auth::AlreadyAuthorizedError to only be raised if credentials actually conflict.
Setting the same credential twice for the same type is ignored.
> Make credentials idempotent

- .travis.yml
- CHANGES.md
- lib/rails/auth/x509/filter/java.rb
- rails-auth.gemspec
- spec/rails/auth/x509/middleware_spec.rb
- Bumped MRI Rubies to the ones that are still supported
- Bumped JRuby to the last 2 releases. This required a change to how
Java certificates are created in test (sun.security.x509.X509CertImpl
can no longer be directly instantiated).
> Bump supported Ruby versions

- .rubocop.yml
- CHANGES.md
- lib/rails/auth/rack.rb
- lib/rails/auth/x509/certificate.rb
- lib/rails/auth/x509/subject_alt_name_extension.rb
- spec/rails/auth/x509/certificate_spec.rb
- spec/rails/auth/x509/subject_alt_name_extension_spec.rb
- spec/support/create_certs.rb
This is useful, because:
1) CN is deprecated and domain information should be provided in the
subjectAltName extension, known as DNS SAN
2) There are some emerging standards that encode identity in the URI SAN
(e.g. [SPIFFE](https://spiffe.io)
> Expose Subject Alternative Name information in the certificate

- CHANGES.md
- lib/rails/auth/x509/middleware.rb
- spec/rails/auth/x509/middleware_spec.rb
- spec/support/create_certs.rb
Since the middleware isn't the one managing the TLS connection, we already have to rely on whatever is managing the TLS connection to verify & pass it down into the Rack environment safely. Verifying it in the middleware simply proves you know the cert (which are more or less public) and doesn't prove ownership of the underlying private key.
> Remove ca_file, require_cert, and truststore options to X509 middleware
